### ISSUE TITLE
apply_esx_network_config failure in dfw2 with 1 esx host

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-vsphere#22]
I'm logging this error (while on b7e4b7a)  incase it comes up again.

```
null_resource.apply_esx_network_config[0]: Still creating... [4m30s elapsed]
null_resource.apply_esx_network_config[0] (remote-exec): There was a connection Error to host: 139.178.87.210. Sleeping 10 seconds and trying again.
null_resource.apply_esx_network_config[0]: Still creating... [4m40s elapsed]
null_resource.apply_esx_network_config[0] (remote-exec): Trying to connect to ESX Host . . .
null_resource.apply_esx_network_config[0] (remote-exec): Connected to ESX Host !
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created vSwitch  vSwitch1
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  VM Private Net 1
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  Management
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  vMotion
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  vSAN
null_resource.apply_esx_network_config[0] (remote-exec): Successfully created PortGroup  VM Public Net 1
null_resource.apply_esx_network_config[0] (remote-exec): Trying to connect to ESX Host . . .
null_resource.apply_esx_network_config[0] (remote-exec): Connected to ESX Host !
null_resource.apply_esx_network_config[0] (remote-exec): Removing vNic: vmk0
null_resource.apply_esx_network_config[0] (remote-exec): Removing Port Group: VM Network
null_resource.apply_esx_network_config[0] (remote-exec): Removing Port Group: Private Network
null_resource.apply_esx_network_config[0] (remote-exec): Traceback (most recent call last):
null_resource.apply_esx_network_config[0] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 353, in <module>
null_resource.apply_esx_network_config[0] (remote-exec):     main()
null_resource.apply_esx_network_config[0] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 260, in main
null_resource.apply_esx_network_config[0] (remote-exec):     host_network_system.RemovePortGroup(pgroup[23:])
null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 706, in <lambda>
null_resource.apply_esx_network_config[0] (remote-exec):     self.f(*(self.args + (obj,) + args), **kwargs)
null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 512, in _InvokeMethod
null_resource.apply_esx_network_config[0] (remote-exec):     return self._stub.InvokeMethod(self, info, args)
null_resource.apply_esx_network_config[0] (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/pyVmomi/SoapAdapter.py", line 1397, in InvokeMethod
null_resource.apply_esx_network_config[0] (remote-exec):     raise obj # pylint: disable-msg=E0702
null_resource.apply_esx_network_config[0] (remote-exec): pyVmomi.VmomiSupport.ResourceInUse: (vim.fault.ResourceInUse) {
null_resource.apply_esx_network_config[0] (remote-exec):    dynamicType = <unset>,
null_resource.apply_esx_network_config[0] (remote-exec):    dynamicProperty = (vmodl.DynamicProperty) [],
null_resource.apply_esx_network_config[0] (remote-exec):    msg = "The resource 'Private Network' is in use.",
null_resource.apply_esx_network_config[0] (remote-exec):    faultCause = <unset>,
null_resource.apply_esx_network_config[0] (remote-exec):    faultMessage = (vmodl.LocalizableMessage) [],
null_resource.apply_esx_network_config[0] (remote-exec):    type = vim.host.PortGroup,
null_resource.apply_esx_network_config[0] (remote-exec):    name = 'Private Network'
null_resource.apply_esx_network_config[0] (remote-exec): }
```

**Comment by displague** [comment]
This is the same as https://github.com/equinix/terraform-metal-vsphere/issues/36. Two esxi nodes were used when that issue was triggered, so this seems unrelated to esxi node count.
