### ISSUE TITLE
Integration tests failing with "object has not Attribute RetrieveContent"

### ISSUE THREAD

**Issue by displague** [equinix/terraform-metal-vsphere#28]
Local and E2E tests are currently failing with:

```
null_resource.apply_esx_network_config[1] (remote-exec): Connected to ESX Host !
null_resource.apply_esx_network_config[1] (remote-exec): Traceback (most recent call last):
null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 353, in <module>
null_resource.apply_esx_network_config[1] (remote-exec):     main()
null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 242, in main
null_resource.apply_esx_network_config[1] (remote-exec):     host, si = connect_to_host(new_ip, options.user, options.pw)
null_resource.apply_esx_network_config[1] (remote-exec):   File "/root/bootstrap/esx_host_networking.py", line 146, in connect_to_host
null_resource.apply_esx_network_config[1] (remote-exec):     content = si.RetrieveContent()
null_resource.apply_esx_network_config[1] (remote-exec): AttributeError: 'NoneType' object has no attribute 'RetrieveContent'
```

**Comment by displague** [comment]
This error is returned after the esx_host_connect function times out after 5 minutes.

The timeout was happening because the gateway node could not reach the esx01/esx02 nodes on the private vlan - 172.16.0.1 -> 172.16.0.4 and 172.16.0.5

The gateway's pre_req.py script is very sensitive to the host configuration and this configuration changed when a bug fix was deployed: https://github.com/packethost/packet-networking/pull/35

The current thinking in solving this problem is to take advantage of hybrid-bonded mode.

An alternative would be to change the pre_reqs.py to find the interfaces in the new order.

Modifying /etc/network/interfaces is tricky business, it may be better in the long term to rely on salt (masterless minion) to make these changes.
